services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dicek
      POSTGRES_PASSWORD: 2546
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: 2546
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - chdata:/var/lib/clickhouse
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.d/custom-users.xml
    networks:
      - mynet

  backend:
    build: ./backend
    container_name: express_api
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: dicek
      POSTGRES_PASSWORD: 2546
      POSTGRES_DB: mydb
      POSTGRES_HOST: postgres
      CLICKHOUSE_HOST: clickhouse_db 
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - clickhouse
    networks:
      - mynet
  frontend:
    build: ./frontend
    container_name: react_ui
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynet
volumes:
  pgdata:
  chdata:
networks:
  mynet:
    driver: bridge
